server:
  port: 8088
spring:
  application:
    name: cart-service
  redis:
    host: 192.168.10.123
    port: 6379
    database: 0

eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
    registry-fetch-interval-seconds: 10
  instance:
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 15

yiport:
  jwt:
    pubKeyPath: D:\DemoFiles\tmp\rsa\\rsa.pub # 公钥地址
    cookieName: YP_TOKEN # cookie的名称