server:
  port: 8085
spring:
  application:
    name: user-service
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/yp_mall?characterEncoding=UTF8&autoReconnect=true&useSSL=false
    username: 'root'
    password: '000000'
    driver-class-name: com.mysql.jdbc.Driver
  redis:
    host: 192.168.10.123
    port: 6379
    database: 0

  rabbitmq:
    host: 192.168.10.123
    username: yiport
    password: yiport
    virtual-host: /yiport

eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
  instance:
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 15

mybatis:
  type-aliases-package: cn.yiport.user.pojo